function row=ramsey_export_run(run,ctx,L,out,w)
e=run.best.evaluation;N=e.problem.T;T=N+L;P=transition_export_path(e.x,e.problem);B=run.baseline.path;
a=e.welfare;b=run.baseline_welfare;private=a.private_value-b.private_value;environment=-(a.discounted_damage-b.discounted_damage);net=private+environment;
row=struct('tools',strjoin(ctx.tools,'+'),'calendar_terminal',T,'announcement_date',L, ...
 'eta',ctx.scenario.eta,'loss_target',ctx.scenario.loss_target,'chi',ctx.scenario.chi, ...
 'consumption_utility_change',private,'environment_welfare_change',environment,'net_welfare_change',net, ...
 'net_gain_in_fixed_anchor_units',net/ctx.anchor,'projected_gradient',run.best.projected_gradient, ...
 'multistart_gain_spread',run.multistart_gain_spread,'upper_bound_active',run.upper_bound_active, ...
 'equilibrium_residual',e.maximum_residual,'terminal_investment_gap',e.terminal_gap, ...
 'passed',run.passed,'global_optimum_certified',false,'zero_rent_corners_included',false);
local_date=(0:N)';calendar_date=local_date+L;resource_tax=e.problem.policy.tau_e_path(:);service_wedge=e.problem.policy.tau_c_s_path(:);
pigou=nan(N+1,1);
if isfield(a,'environment_costate_discounted')
 mu=P.E.^(e.problem.p.epsilon-1).*P.P_star.^(-e.problem.p.epsilon);
 for t=0:N-1
  mec=e.problem.p.beta^(-t)*ctx.local_climate.a'*a.environment_costate_discounted(:,t+2)/ctx.anchors.e_reference;
  pigou(t+1)=mec/(mu(t+1)*P.h(t+1));
 end
rgrad=nan(N+1,1);sgrad=rgrad;
for k=1:numel(ctx.tools)
 v=[-e.gradient((k-1)*N+(1:N));NaN];
 if strcmp(ctx.tools{k},'resource'),rgrad=v;else,sgrad=v;end
end
t=table(calendar_date,local_date,resource_tax,service_wedge,pigou,rgrad,sgrad, ...
 P.R_input(:),B.R_input(:),a.environment.M(:),b.environment.M(:),P.K(:),B.K(:),P.R(:),B.R(:), ...
 'VariableNames',{'calendar_date','local_date','resource_tax','service_wedge','conditional_pigou_tax', ...
 'resource_log_wedge_welfare_gradient_in_anchor_units','service_log_wedge_welfare_gradient_in_anchor_units', ...
 'policy_extraction','baseline_extraction','policy_burden','baseline_burden','policy_capital','baseline_capital','policy_reserves','baseline_reserves'});
writetable(t,fullfile(out,sprintf('ramsey_path_T%d.csv',T)));
writetable(struct2table(run.best.history),fullfile(out,sprintf('ramsey_iterations_T%d.csv',T)));
end
end
