function v = transition_validate_solution(x,q,tolerance)
if nargin<3,tolerance=1e-9;end
[F,d]=transition_global_residual(x,q);X=d.state;j=1:q.T;next=j+1;
K=X(1,:);R=X(2,:);
local_K=(K(next)-(1-q.p.delta)*K(j)-d.I(j))./K(next);
local_R=(R(next)-R(j)+d.e(j))./R(j);
resource_budget=(R(1)-sum(d.e(j))-R(end))/R(1);
checks=struct('global_residual',max(abs(F))<=tolerance, ...
    'static_accounting',max(d.static_equation_max)<=tolerance, ...
    'local_capital_law',max(abs(local_K))<=tolerance, ...
    'local_resource_law',max(abs(local_R))<=tolerance, ...
    'resource_budget',abs(resource_budget)<=tolerance, ...
    'feasible',d.all_feasible,'no_clamps',isempty(d.clamp_times), ...
    'capital_law_implies_positive_investment',all(K(next)>(1-q.p.delta)*K(j)), ...
    'resource_stock_decreases',all(R(next)<R(j)));
names=fieldnames(checks);passed=true;
for k=1:numel(names),passed=passed&&checks.(names{k});end
v=struct('passed',passed,'tolerance',tolerance,'checks',checks,'residual',F,'diagnostics',d, ...
    'local_capital_residuals',local_K,'local_resource_residuals',local_R, ...
    'resource_budget_residual',resource_budget,'finite_horizon_equilibrium_validated',passed, ...
    'infinite_horizon_approximation_validated',false);
end
