function [F,d] = transition_global_residual(x,q)
X=transition_unpack_path(x,q);p=q.p;N=q.T+1;
for j=1:N
    z=struct('K',X(1,j),'R',X(2,j),'r',X(3,j),'h',X(4,j),'E',X(5,j));
    tech=struct('A_m',q.technology(1,j),'A_s',q.technology(2,j), ...
        'A_x',q.technology(3,j),'A_e',q.technology(4,j));
    pol=struct('tau_c_m',q.policy.tau_c_m_path(j),'tau_c_s',q.policy.tau_c_s_path(j), ...
        'tau_int',q.policy.tau_int_path(j),'tau_e',q.policy.tau_e_path(j), ...
        'tau_x',q.policy.tau_x_path(j));
    if isfield(q,'investment_policy_kind'),pol.investment_policy_kind=q.investment_policy_kind;end
    sj=transition_static_kernel(z,tech,pol,p,q.mode);
    if j==1,S=repmat(sj,1,N);end
    S(j)=sj;
end
F=zeros(q.n,1);
for j=1:q.T
    purchase=isfield(q,'investment_policy_kind')&&strcmp(q.investment_policy_kind,'purchase_subsidy');
    dynamic=transition_intertemporal_residual(X(5,j),X(5,j+1),S(j).P_star,S(j+1).P_star, ...
        X(3,j+1),X(4,j),X(4,j+1),p,q.policy.tau_x_path(j),q.policy.tau_x_path(j+1),q.mode,purchase);
    rows=5*(j-1)+(1:5);
    F(rows)=[S(j).capital_residual; ...
        (X(1,j+1)-(1-p.delta)*X(1,j)-S(j).I)/q.reference(1,j+1); ...
        (X(2,j+1)-X(2,j)+S(j).e)/q.reference(2,j); ...
        dynamic(1); ...
        dynamic(2)];
end
F(5*q.T+(1:2))=[log(X(1,1)/q.targets.K0);log(X(2,1)/q.targets.R0)];
z=struct('K',X(1,N),'R',X(2,N),'r',X(3,N),'h',X(4,N),'E',X(5,N));
F(5*q.T+(3:5))=transition_terminal_boundary(z,S(N),q);
assert(isreal(F)&&all(isfinite(F)),'v2:Residual','Nonfinite equilibrium residual');
if nargout>1
    [~,bd]=transition_terminal_boundary(z,S(N),q);
    [maxF,idx]=max(abs(F));groupmax=zeros(1,10);
    for k=1:10,groupmax(k)=max(abs(F(q.groups{k})));end
    sr=reshape([S.residuals],numel(S(1).residuals),N);
    d=struct('max_equilibrium_residual',maxF,'worst_row',q.row_names{idx}, ...
        'equation_names',{q.equation_names},'equation_max',groupmax, ...
        'static_residual_names',{S(1).residual_names},'static_residuals',sr, ...
        'static_equation_max',max(abs(sr),[],2),'capital_residuals',[S.capital_residual], ...
        'feasible_by_node',[S.feasible],'all_feasible',all([S.feasible]), ...
        'infeasible_times',q.time(~[S.feasible]),'clamp_times',q.time([S.clamp_active]), ...
        'minimum_consumption',min([[S.c_m],[S.c_s]]), ...
        'minimum_investment',min([S.I]),'minimum_extraction',min([S.e]), ...
        'maximum_extraction_stock_ratio',max([S.e]./X(2,:)), ...
        'terminal',bd,'state',X,'I',[S.I],'e',[S.e],'P_star',[S.P_star]);
end
end
