function c=paper_figure_config()
root=fileparts(fileparts(mfilename('fullpath')));
c.results=fullfile(root,'results','paper');
c.output=fullfile(root,'outputs','paper_figures');
c.appendix_output=fullfile(root,'outputs','appendix_figures');
c.transition=fullfile(c.results,'transition');
c.horizon=fullfile(c.results,'horizon');
c.cf=struct('report_file',fullfile(c.results,'counterfactual','counterfactual_report.mat'), ...
 'destination',c.output, ...
 'policy_ids',{{'service_temporary','consumption_temporary'}},'last_date',40);
c.welfare=struct('destination',c.output,'make_tables',false,...
 'climate_report_file',fullfile(c.results,'climate','climate_report.mat'), ...
 'welfare_report_file',fullfile(c.results,'welfare','industrial_welfare_report.mat'), ...
 'ramsey_report_file',fullfile(c.results,'ramsey','ramsey_report.mat'), ...
 'shared_report_file',fullfile(c.results,'shared_state','ramsey_shared_state_report.mat'), ...
 'T',200,'eta',2,'loss_target',.01,'last_local_date',80);
c.measurement=struct('destination',c.appendix_output, ...
 'case_ids',{{'annual_average','domestic_inputs','mapping_c26'}}, ...
 'case_labels',{{'Annual average','Domestic inputs','C26 mapping'}});
end
