function policies = policy_config(model)

policies(1)=struct( ...
    'id','service_temporary', ...
    'start',0, 'duration',10, 'permanent',false, ...
    'tau_c_m',0, 'tau_c_s',-0.2, ...
    'tau_int',0, 'tau_e',0, 'tau_x',0, ...
    'investment_policy_kind','none');

policies(2)=struct( ...
    'id','service_permanent', ...
    'start',0, 'duration',10, 'permanent',true, ...
    'tau_c_m',0, 'tau_c_s',-0.2, ...
    'tau_int',0, 'tau_e',0, 'tau_x',0, ...
    'investment_policy_kind','none');

policies(3)=struct( ...
    'id','consumption_temporary', ...
    'start',0, 'duration',10, 'permanent',false, ...
    'tau_c_m',0.2, 'tau_c_s',0.2, ...
    'tau_int',0, 'tau_e',0, 'tau_x',0, ...
    'investment_policy_kind','none');

policies(4)=struct( ...
    'id','consumption_permanent', ...
    'start',0, 'duration',10, 'permanent',true, ...
    'tau_c_m',0.2, 'tau_c_s',0.2, ...
    'tau_int',0, 'tau_e',0, 'tau_x',0, ...
    'investment_policy_kind','none');

policies(5)=struct( ...
    'id','carbon_temporary', ...
    'start',0, 'duration',10, 'permanent',false, ...
    'tau_c_m',0, 'tau_c_s',0, ...
    'tau_int',0, 'tau_e',0.2, 'tau_x',0, ...
    'investment_policy_kind','none');

policies(6)=struct( ...
    'id','investment_purchase_20', ...
    'start',0, 'duration',10, 'permanent',false, ...
    'tau_c_m',0, 'tau_c_s',0, ...
    'tau_int',0, 'tau_e',0, 'tau_x',-0.2, ...
    'investment_policy_kind','purchase_subsidy');

policies(7)=struct( ...
    'id','investment_purchase_matched', ...
    'start',0, 'duration',10, 'permanent',false, ...
    'tau_c_m',0, 'tau_c_s',0, ...
    'tau_int',0, 'tau_e',0, 'tau_x',-1/6, ...
    'investment_policy_kind','purchase_subsidy');

if strcmp(model,'legacy'),policies=policies(1:5);end
end
