function plot_Figure2_PolicyDeviations()
    clc; clear; close all;

% Input the path to the 'service_subsidy_10_periods.mat' file located in the Sim_Results directory, 
% or input the path to any custom data file generated by the simulation program.
    file_path = 'Sim_Results\service_subsidy_10_periods.mat';
    
    obs_period = 40; 
    
    if ~exist(file_path, 'file')
        error('File not found. Please specify the correct data path.');
    end
    load(file_path, 'SimData');
    
    Base = SimData.BaseRes;
    Final = SimData.FinalRes;
    BasePol = SimData.BasePol;
    TargetPol = SimData.TargetPol;
    
    time = 0:obs_period;
    
    L_in_base = Base.l_m(1:obs_period+1) + Base.l_s(1:obs_period+1);
    Share_Ls_base = Base.l_s(1:obs_period+1) ./ L_in_base;
    
    L_in_pol = Final.l_m(1:obs_period+1) + Final.l_s(1:obs_period+1);
    Share_Ls_pol = Final.l_s(1:obs_period+1) ./ L_in_pol;
    
    dev_Ls_pp = (Share_Ls_pol - Share_Ls_base) * 100;
    
    Inv_exp_base = Base.I(1:obs_period+1) .* (1 + BasePol.tau_x_path(1:obs_period+1));
    Inv_rate_base = Inv_exp_base ./ Base.Y_GDP(1:obs_period+1);
    
    Inv_exp_pol = Final.I(1:obs_period+1) .* (1 + TargetPol.tau_x_path(1:obs_period+1));
    Inv_rate_pol = Inv_exp_pol ./ Final.Y_GDP(1:obs_period+1);
    
    dev_InvRate_pp = (Inv_rate_pol - Inv_rate_base) * 100;
    
    e_Y_base = Base.R_input(1:obs_period+1) ./ Base.Y_GDP(1:obs_period+1);
    e_Y_pol = Final.R_input(1:obs_period+1) ./ Final.Y_GDP(1:obs_period+1);
    
    dev_eY_pct = (e_Y_pol ./ e_Y_base - 1) * 100;
    
    dev_R_pct = (Final.R(1:obs_period+1) ./ Base.R(1:obs_period+1) - 1) * 100;
    dev_I_pct = (Final.I(1:obs_period+1) ./ Base.I(1:obs_period+1) - 1) * 100;
    dev_e_pct = (Final.R_input(1:obs_period+1) ./ Base.R_input(1:obs_period+1) - 1) * 100;

    figure('Name', 'Figure 2: Policy Deviations', 'Color', 'w', 'Position', [150, 150, 1400, 800]);
    
    lw = 2.5; 
    fs = 14;  

    subplot(2, 3, 1);
    plot(time, dev_R_pct, 'r-', 'LineWidth', lw);
    title('\Delta Resource Stock R (%)', 'FontSize', fs);
    ylabel('% Deviation');
    apply_format(obs_period);

    subplot(2, 3, 2);
    plot(time, dev_I_pct, 'g-', 'LineWidth', lw);
    title('\Delta Investment Level I (%)', 'FontSize', fs);
    ylabel('% Deviation');
    apply_format(obs_period);

    subplot(2, 3, 3);
    plot(time, dev_InvRate_pp, 'g-', 'LineWidth', lw);
    title('\Delta Inv. Rate (I/GDP) (pp)', 'FontSize', fs);
    ylabel('Percentage Points');
    apply_format(obs_period);

    subplot(2, 3, 4);
    plot(time, dev_Ls_pp, 'r-', 'LineWidth', lw);
    title('\Delta Labor Share: Services (pp)', 'FontSize', fs);
    ylabel('Percentage Points');
    apply_format(obs_period);

    subplot(2, 3, 5);
    plot(time, dev_e_pct, 'm-', 'LineWidth', lw);
    title('\Delta Extraction Flow e (%)', 'FontSize', fs);
    ylabel('% Deviation');
    apply_format(obs_period);

    subplot(2, 3, 6);
    plot(time, dev_eY_pct, 'm-', 'LineWidth', lw);
    title('\Delta e/Y Ratio (%)', 'FontSize', fs);
    ylabel('% Deviation');
    apply_format(obs_period);
    
    fprintf('Figure 2 rendered successfully.\n');
end

function apply_format(obs_p)
    yline(0, 'k--', 'LineWidth', 1); 
    set(gca, 'FontSize', 11, 'TickDir', 'out');
    grid on;
    xlim([0, obs_p]);
end