function files=climate_export_parameters(report,out)
r=report.main;m=report.configuration;
tab=struct2table(r.scenarios);writetable(tab,fullfile(out,'climate_scenarios.csv'));
s=r.trajectory;T=r.T;dates=(0:T)';H=s.B(:);future=s.M(:)-H;
trajectory=table(dates,r.baseline.path.R_input(:),s.q(:),s.M(:),H,future, ...
 'VariableNames',{'date','extraction_model_units','normalized_extraction','total_burden','inherited_burden','future_emission_burden'});
for k=1:4,trajectory.(sprintf('component_%d',k))=s.C(k,:)';end
for k=1:numel(m.etas)
 eta=m.etas(k);idx=find([r.scenarios.eta]==eta&[r.scenarios.loss_target]==m.benchmark_loss,1);
 chi=r.scenarios(idx).chi;pC=nan(4,T+1);
 d=r.environment_tail_details{k};pC(:,end)=chi*d.gradient_total_state(1:4);
 for t=T-1:-1:m.L
  Dprime=eta*s.M(t+1)^(eta-1)/r.anchors.M_reference^eta;
  pC(:,t+1)=chi*Dprime*ones(4,1)+r.baseline.p.beta*m.rho.*pC(:,t+2);
 end
 MEC=nan(T+1,1);
 for t=m.L:T-1,MEC(t+1)=r.baseline.p.beta*m.a'*pC(:,t+2)/r.anchors.e_reference;end
 trajectory.(sprintf('marginal_environment_cost_eta%d_utility_per_model_resource',eta))=MEC;
end
writetable(trajectory,fullfile(out,'climate_baseline_path.csv'));
aa=struct2table(report.horizon_audit);writetable(aa,fullfile(out,'climate_horizon_audit.csv'));
parameters=struct('version',1,'ready_for_policy_optimization',report.passed, ...
 'model_mode','paper','economic_parameters',m.base.p,'original_targets',m.base.targets, ...
 'original_A0',m.base.A0,'announcement_date',m.L,'inherited',r.inherited, ...
 'a',m.a,'rho',m.rho,'timescales_years',m.timescales_years,'kernel_source',m.kernel_source, ...
 'normalization',r.anchors,'etas',m.etas,'loss_definition',m.loss_definition,'scenarios',r.scenarios, ...
 'benchmark',r.benchmark,'initial_components',m.initial_components, ...
 'physical_emissions_calibrated',false,'empirical_damage_estimate',false, ...
 'policy_optimized',false,'utility_calibration_tail_numerically_converged',true, ...
 'zero_pre_model_burden',all(m.initial_components==0), ...
 'environment_tail_assumption','ABGP extraction tail and fixed Joos kernel extrapolation');
save(fullfile(out,'climate_parameters.mat'),'parameters');
files=struct('parameters',fullfile(out,'climate_parameters.mat'), ...
 'scenarios',fullfile(out,'climate_scenarios.csv'),'path',fullfile(out,'climate_baseline_path.csv'), ...
 'horizon',fullfile(out,'climate_horizon_audit.csv'));
end
