function m = transition_baseline_moments(path)
assert(numel(path.K)>=15,'v2:Moments','Need dates 0:14');
idx=1:15;E=path.E(idx);I=path.I(idx);K=path.K(idx);
E=E(:).';I=I(:).';K=K(:).';
pm=path.p_m(idx);ps=path.p_s(idx);cm=path.c_m(idx);cs=path.c_s(idx);
sm=pm(:).'.*cm(:).'./E;ss=ps(:).'.*cs(:).'./E;
assert(all(isfinite([E,I,K,sm,ss]))&&all(E>0)&&all(E+I>0), ...
    'v2:Moments','Invalid early-window moment data');
assert(max(abs(sm+ss-1))<1e-9,'v2:Moments','Consumption shares do not sum to one');
m=struct('capital_output_ratio_t0',K(1)/(E(1)+I(1)), ...
    'service_consumption_share_t0',ss(1),'service_consumption_share_t14',ss(15), ...
    'service_share_change_0_14_pp',100*(ss(15)-ss(1)), ...
    'service_share_relative_change_0_14_percent',100*(ss(15)/ss(1)-1), ...
    'manufacturing_share_change_0_14_pp',100*(sm(15)-sm(1)), ...
    'manufacturing_share_relative_change_0_14_percent',100*(sm(15)/sm(1)-1), ...
    'nominal_final_output_t0',E(1)+I(1),'empirical_targets_available',false, ...
    'empirical_fit_validated',false);
end
