function d = transition_resource_decomposition(path,policy,base,base_policy,p,dates)
if nargin<6,dates=[0,10];end
a=resource_objects(path,policy,p);b=resource_objects(base,base_policy,p);
assert(numel(a.e)==numel(b.e)&&numel(dates)==2&&all(dates==fix(dates)) ...
    &&dates(1)>=0&&dates(2)>dates(1)&&dates(2)<numel(a.e), ...
    'v2:Decomposition','Invalid paths or comparison dates');
de=log(a.e)-log(b.e);dh=log(a.h_star)-log(b.h_star);
dy=log(a.Y)-log(b.Y);db=log(a.beta_bar)-log(b.beta_bar);
ia=dates(1)+1;ib=dates(2)+1;
components=[dh(ib)-dh(ia),dy(ia)-dy(ib),db(ia)-db(ib)];
total=de(ia)-de(ib);
adjacent=[diff(dh);-diff(dy);-diff(db)];
adjacent_total=-diff(de);
from_initial=[dh-dh(1);dy(1)-dy;db(1)-db];
from_initial_total=de(1)-de;
share=NaN(1,3);absolute_share=share;
if abs(total)>1e-8,share=components/total;end
if sum(abs(components))>1e-8,absolute_share=abs(components)/sum(abs(components));end
d=struct('dates',dates,'component_names',{{'Hotelling','Growth','Structural Change'}}, ...
    'total_log_deviation',total,'component_log_deviations',components, ...
    'total_log_points',100*total,'component_log_points',100*components, ...
    'exact_extraction_ratio_change_percent',100*expm1(total), ...
    'signed_component_shares',share,'absolute_component_shares',absolute_share, ...
    'share_denominator_near_zero',abs(total)<=1e-8, ...
    'endpoint_identity_error',abs(total-sum(components)), ...
    'adjacent_identity_error',max(abs(adjacent_total-sum(adjacent,1))), ...
    'initial_to_each_date_identity_error',max(abs(from_initial_total-sum(from_initial,1))), ...
    'extraction_identity_error',max(a.extraction_identity_error,b.extraction_identity_error), ...
    'adjacent_component_log_deviations',adjacent,'adjacent_total_log_deviation',adjacent_total, ...
    'initial_to_each_date_components',from_initial,'initial_to_each_date_total',from_initial_total, ...
    'policy_objects',a,'baseline_objects',b,'causal_channel_counterfactuals',false);
assert(max([d.endpoint_identity_error,d.adjacent_identity_error, ...
    d.initial_to_each_date_identity_error,d.extraction_identity_error])<1e-9, ...
    'v2:Decomposition','Exact extraction decomposition failed');
end

function a=resource_objects(path,policy,p)
V=[path.p_m(:).'.*path.c_m(:).';path.p_s(:).'.*path.c_s(:).';path.I(:).'];
Y=sum(V,1);beta_bar=[p.beta_m,p.beta_s,p.beta_x]*V./Y;
h_star=path.h(:).'.*(1+policy.tau_e_path(:).').*(1+policy.tau_int_path(:).');
e=path.R_input(:).';
assert(all(isfinite([V(:);Y(:);beta_bar(:);h_star(:);e(:)])) ...
    &&all(V(:)>0)&&all(h_star>0)&&all(e>0),'v2:Decomposition','Invalid economic objects');
a=struct('Y',Y,'beta_bar',beta_bar,'revenue_shares',V./Y,'h_star',h_star,'e',e, ...
    'resource_intensity',e./Y, ...
    'extraction_identity_error',max(abs(p.beta_e*Y.*beta_bar./h_star./e-1)));
end
